version: "3.9"

networks:
  app-network:
    driver: bridge

services:

  redis:
    image: redis:7
    container_name: redis
    networks:
      - app-network
    restart: always
    expose:
      - "6379"

  api:
    build: ./api
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_started
    environment:
      - REDIS_HOST=redis
    networks:
      - app-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  worker:
    build: ./worker
    container_name: worker
    depends_on:
      redis:
        condition: service_started
      api:
        condition: service_started
    environment:
      - REDIS_HOST=redis
    networks:
      - app-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_started
    networks:
      - app-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M