name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------- PYTHON ----------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install lint tools
        run: pip install flake8

      - name: Lint Python code
        run: flake8 API worker

      # ---------- NODE (Frontend) ----------
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install frontend deps
        run: |
          cd frontend
          npm install

      # ---------- DOCKER ----------
      - name: Install hadolint
        run: |
          wget -O hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x hadolint
          sudo mv hadolint /usr/local/bin/

      - name: Lint Dockerfiles
        run: |
          hadolint API/Dockerfile || true
          hadolint worker/Dockerfile || true
          hadolint frontend/Dockerfile || true